version: '3'

services:      
    receiver:
        image: tu-app-receiver:1.0
        container_name: "receiver"
        restart: on-failure
        ports:
            - "8081:8080"
        networks:
            - tu-network
            
    sender-1:
        image: tu-app-faculty-sender:1.0
        container_name: "faculty-sender-1"
        restart: on-failure
        ports:
            - "8082:8080"
        networks:
            - tu-network
            
    sender-2:
        image: tu-app-faculty-sender:1.0
        container_name: "faculty-sender-2"
        restart: on-failure
        ports:
            - "8083:8080"
        networks:
            - tu-network
            
    message-queue:
        image: rabbitmq:latest
        container_name: "rabbit-mq"
        ports:
            - "5672:5672"
        networks:
            - tu-network

networks:
  tu-network: